languages:
  Ruby: false
  JavaScript: true
  PHP: false
  Python: false

engines:
  csslint:
    enabled: true
 ratings:
    paths:
      - "**.css"

exclude_paths:
- "amp/src/main/amp/web/scripts/bulkimport/smoothie.js"
- "test/data/"
